In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\User\Downloads\Bi Project\customer_shopping_behavior.csv")

ModuleNotFoundError: No module named 'pandas'

In [26]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [28]:
df.describe(include= 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [29]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [30]:
#find the median review rating for each category and use this for the missing review rating

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x .median()))

In [31]:
#fix the column name format

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [32]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [33]:
# a more descriptive age group

labels = ['Young Adult', 'Adult', 'Middle Age', 'Senior']
df['age_group'] = pd.qcut(df['age'], 4, labels=labels)

In [34]:
df[['age', 'age_group']]

      age    age_group
0      55   Middle Age
1      19  Young Adult
2      50   Middle Age
3      21  Young Adult
4      45   Middle Age
...   ...          ...
3895   40        Adult
3896   52   Middle Age
3897   46   Middle Age
3898   44        Adult
3899   52   Middle Age

[3900 rows x 2 columns]

In [35]:
df.frequency_of_purchases.unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [36]:
#improve the frequencey of purchases column

purchase_frequency_map = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Bi-Weekly' : 14,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Every 3 Months' : 90,
    'Annually' : 365
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(purchase_frequency_map)

In [37]:
df.purchase_frequency_days

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: purchase_frequency_days, Length: 3900, dtype: int64

In [38]:
df[['frequency_of_purchases', 'purchase_frequency_days']]

     frequency_of_purchases  purchase_frequency_days
0               Fortnightly                       14
1               Fortnightly                       14
2                    Weekly                        7
3                    Weekly                        7
4                  Annually                      365
...                     ...                      ...
3895                 Weekly                        7
3896              Bi-Weekly                       14
3897              Quarterly                       90
3898                 Weekly                        7
3899              Quarterly                       90

[3900 rows x 2 columns]

In [39]:
df['purchase_frequency_days']

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: purchase_frequency_days, Length: 3900, dtype: int64

In [40]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [41]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [42]:
#drop promo_code_used since it has the same information as discount applied

df = df.drop('promo_code_used', axis=1)

In [43]:
df.head(5)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Age,365

In [44]:
! pip install ipython-sql pymysql cryptography
! pip install pymysql pandas sqlalchemy

Requirement already satisfied: ipython-sql in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.5.0)
Requirement already satisfied: pymysql in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.0)
Requirement already satisfied: cryptography in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (50.0.1)
Requirement already satisfied: prettytable in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython-sql) (3.18.0)
Requirement already satisfied: ipython in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython-sql) (9.15.0)
Requirement already satisfied: sqlalchemy>=2.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython-sql) (2.0.53)
Requirement already satisfied: sqlparse in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython-sql) (0.6.0)
Requirement already satisfied: six in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cryptography) (2.1.1)
Requirement already satisfied: pycparser in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cffi>=2.0.0->cryptography) (3.0)
Requirement already satisfied: greenlet>=1 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.16.0)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: psutil>=7 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (5.15.1)
Requirement already satisfied: wcwidth in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.2->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)
Requirement already satisfied: pymysql in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.0)
Requirement already satisfied: pandas in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.53)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: greenlet>=1 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from sqlalchemy import create_engine

# 1. Establish the connection to MySQL server instance
# Format: mysql+pymysql://username:password@host:port/database_name
engine = create_engine("mysql+pymysql://root:hervoiceafrica@127.0.0.1:3306/shoba")

# 2. Push your DataFrame to MySQL
# Replace 'your_dataframe_variable' with the actual name of your Python DataFrame
# Replace 'new_table_name' with whatever you want to name this table in SQL
df.to_sql(
    name='customer_behaviour_data', 
    con=engine, 
    if_exists='fail',   # Options: 'fail' (errors out if table exists), 'replace', or 'append'
    index=False         # Set to False if you don't want the DataFrame index as a separate SQL column
)

print("Data successfully uploaded to MySQL!")

Data successfully uploaded to MySQL!

In [46]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Age,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle Age,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle Age,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle Age,90